###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "nuevoUsuario",
  "email": "nuevo@email.com",
  "password": "12345678"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "nuevo@email.com",
  "password": "12345678"
}